server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: S1V1sP4c3mP4r4B3llum
        url: jdbc:mysql://localhost:3306/develhope_clinic_db
        username: root
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
